language: java
addons:
  apt:
    packages:
    - "cmake"

cache:
  directories:
  - "/tmp/dlib"

before_install:
- ./dlib-java make-dlib

script:
- ./dlib-java mvn-package

after_script:
- ./dlib-java java-jar